name: dog_breeds
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.10
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  carousel_slider: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/dog-breeds.json
    - assets/images/basset.jpg
    - assets/images/beagle.png
    - assets/images/border-collie.jpg
    - assets/images/bull-terrier.png
    - assets/images/bulldog-frances.jpg
    - assets/images/cachorro-caramelo.jpg
    - assets/images/chihuahua.jpg
    - assets/images/cocker-spaniel.jpg
    - assets/images/dachshund.jpg
    - assets/images/golden-retriever.jpg
    - assets/images/labrador.jpg
    - assets/images/pastor-alemao.png
    - assets/images/pastor-australiano.jpg
    - assets/images/poodle-gigante.jpg
    - assets/images/poodle-medio.jpg
    - assets/images/poodle-toy.png
    - assets/images/pug.jpg
    - assets/images/rottweiler.jpg
    - assets/images/yorkshire.jpg

